sudo: false
dist: trusty

language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - rustc --version
  - ci/install-h2spec.sh
  - export PATH="$PATH:$(pwd)"
  - export RUST_BACKTRACE=1

script:
  - cargo test -- --test-threads=1
  - cargo test --benches
  - cargo run --manifest-path h2spec-test/Cargo.toml --bin the_test

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
