sudo: false
dist: trusty

language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - rustc --version
  - RUST_BACKTRACE=1 cargo test
  # cargo test --benches only works in nighly
  #- RUST_BACKTRACE=1 cargo test --benches
  - RUST_BACKTRACE=1 cargo bench

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
