[package]
name = "httpbis-interop"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
version = "0.0.0"

[[bin]]
name = "http2-rust-interop-server"
path = "src/interop_server.rs"

[[bin]]
name = "http2-rust-interop-client"
path = "src/interop_client.rs"

[dependencies.httpbis]
path = "../.."

[dependencies]
bytes      = "0.*"
log        = "0.*"
env_logger = "0.*"
futures    = "0.*"
clap       = "2.*"
native-tls = "0.*"
